% constants and configuration of the project

function cfg = config()
    clc; close all;

    % setup the path
    project_root = fileparts(mfilename('fullpath')); % Get project root
    src_path = fullfile(project_root, 'src');
    if ~contains(path, src_path)
        addpath(genpath(src_path));
    end

    cfg = struct();
    cfg.mapping_params = struct();
    cfg.mapping_params.Nbps = 4;
    cfg.mapping_params.modulation = 'qam';
    cfg.NumBits = 1000; % Number of bits generated by the source

end
